# Generated by Django 4.2.4 on 2023-10-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
