# Generated by Django 4.2.4 on 2023-10-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thread_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
