# Generated by Django 4.2.4 on 2023-10-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_thread_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
    ]
