# Generated by Django 4.2.4 on 2023-10-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_useraccount_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
