# Generated by Django 4.2.4 on 2023-10-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_useraccount_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='remaining_subscription_days',
            field=models.IntegerField(default=0),
        ),
    ]
