# Generated by Django 4.2.4 on 2023-10-04 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_playlist_video_delete_course_playlist_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
        migrations.AddField(
            model_name='playlist',
            name='videos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='mentors.video'),
        ),
    ]
