# Generated by Django 4.2.4 on 2023-10-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0008_playlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
    ]
